### ISSUE TITLE
PSP DLC does not transfer

### ISSUE THREAD

**Issue by aro24** [LiEnby/chovy-trans#7]
With the removal of PS3 to PS Vita content manager support last year, it is much harder to transfer PSP content from the PS3 store to the PS Vita. 

I managed to transfer over a downloaded game (Valkyria Chronicles II) from the PSP to my PS Vita. However the downloadable content/add-ons on the PSP for the game have not transferred to the Vita backup directory on my PC.

**Comment by LiEnby** [comment]
Its funny you say this because i was just looking at PSP DLC, (it could be helpful for regions who do not have a free PSP game. for i.e chovy-sign).. i think it would be pretty easy to make this also transfer PSP DLC after seeing it, since they seem to be ,edat files, and i assume there license is just included inside the license.psvimg, but id have to look more ..

**Comment by LiEnby** [comment]
Finally added this in--
